//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningLineBotApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CLuc3B+qzeEyQmcFTsfmeUavnzpNawYxwb/Pc0rGQjcMpmhHvIePz1N9QVYjCywKZ9Rn5vQLKMf2dyr8o" +
            "Qc1HxsM20JpOQbILkaqHBnls3eNAXkFDfIp8on2vL0Ls8/V/yPdoZufm1OKOPCBIn0s7gdB04t89/1O/" +
            "w1cDnyilFU=")]
        public string accessToken {
            get {
                return ((string)(this["accessToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("896d1d6a1736d80c90021caf956d945f")]
        public string channelSecret {
            get {
                return ((string)(this["channelSecret"]));
            }
        }
    }
}
