//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ICRM01801 {
    
    private ICRM01801IDOCICRM018[][] iDOCField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ICRM018", typeof(ICRM01801IDOCICRM018), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ICRM01801IDOCICRM018[][] IDOC {
        get {
            return this.iDOCField;
        }
        set {
            this.iDOCField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ICRM01801IDOCICRM018 {
    
    private string bRANCH_CODEField;
    
    private string rONOField;
    
    private string cOMPLETION_DATEField;
    
    private ICRM01801IDOCICRM018DETAILS[] dETAILSField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BRANCH_CODE {
        get {
            return this.bRANCH_CODEField;
        }
        set {
            this.bRANCH_CODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RONO {
        get {
            return this.rONOField;
        }
        set {
            this.rONOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string COMPLETION_DATE {
        get {
            return this.cOMPLETION_DATEField;
        }
        set {
            this.cOMPLETION_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DETAILS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ICRM01801IDOCICRM018DETAILS[] DETAILS {
        get {
            return this.dETAILSField;
        }
        set {
            this.dETAILSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ICRM01801IDOCICRM018DETAILS {
    
    private string sOURCESYSTEMField;
    
    private string bRANCH_CODEField;
    
    private string rONOField;
    
    private string aNSWER_CODEField;
    
    private string rESULTSField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SOURCESYSTEM {
        get {
            return this.sOURCESYSTEMField;
        }
        set {
            this.sOURCESYSTEMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BRANCH_CODE {
        get {
            return this.bRANCH_CODEField;
        }
        set {
            this.bRANCH_CODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RONO {
        get {
            return this.rONOField;
        }
        set {
            this.rONOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ANSWER_CODE {
        get {
            return this.aNSWER_CODEField;
        }
        set {
            this.aNSWER_CODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RESULTS {
        get {
            return this.rESULTSField;
        }
        set {
            this.rESULTSField = value;
        }
    }
}
